version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - network1
  sellerapp:
      image: sellerapp
      ports:
      - "50051:50051"
      networks:
      - network1
      depends_on:
      - "mongodb"

volumes:
   mongodata:

networks:
   network1:
    driver: bridge